apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-flask-service
spec:
  type: NodePort
  selector:
    app: simple-webapp-flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007
