name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/flask-app:latest .

    # Step 4: Push Docker Image to GHCR
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/flask-app:latest

    # Step 5: Set up kubectl (Kubeconfig pointing to ngrok URL)
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 6: Deploy to Kubernetes using ngrok URL
    - name: Deploy to Kubernetes
      env:
        KUBERNETES_SERVER: https://abc123.ngrok.io
      run: |
        kubectl config set-cluster kind-kind --server=$KUBERNETES_SERVER
        kubectl set image deployment/flask-app-deployment simple-webapp-flask=ghcr.io/${{ github.repository_owner }}/flask-app:latest
        kubectl rollout status deployment/flask-app-deployment
